language: scala
os:
  - linux
script:
  - sbt ++$TRAVIS_SCALA_VERSION clean "flaky times=30"
scala:
  - 2.12.3
jdk:
  - oraclejdk8
sudo: false
notifications:
  email:
    - krzysztof.otrebski@gmail.com
cache:
  directories:
  - $HOME/.sbt/1.0
  - $HOME/.sbt/boot/scala*
  - $HOME/.sbt/cache
  - $HOME/.sbt/launchers
  - $HOME/.ivy2
  - $TRAVIS_BUILD_DIR/history
before_cache:
  - du -h -d 1 $HOME/.ivy2/
  - du -h -d 2 $HOME/.sbt/
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete

deploy:
  provider: bitballoon
  skip_cleanup: true
  site-id:
    secure: "$SITE_ID"
  access-token:
    secure: "$ACCESS_TOKEN"
  local-dir: "target/flaky-test-reports-html"